### ISSUE TITLE
materialize-css not found

### ISSUE THREAD

**Issue by shokai** [nekobato/Polidium#4]
ぬい

    % npm run webpack

```
> Polidium@0.0.2 webpack /Users/sho/src/nodejs/Polidium
> webpack

Hash: 3222ad9fbe3c9e87f7a0
Version: webpack 1.12.13
Time: 4603ms
        Asset     Size  Chunks             Chunk Names
    script.js  1.43 MB       0  [emitted]  script
script.js.map  1.54 MB       0  [emitted]  script
    + 58 hidden modules

ERROR in ./~/materialize-css/dist/font/material-design-icons/Material-Design-Icons.eot
Module build failed: Error: Cannot find module 'file-loader'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports (/Users/sho/src/nodejs/Polidium/node_modules/url-loader/index.js:18:20)
 @ ./~/css-loader!./~/materialize-css/dist/css/materialize.min.css 6:40920-40986

ERROR in ./~/materialize-css/dist/font/material-design-icons/Material-Design-Icons.ttf
Module build failed: Error: Cannot find module 'file-loader'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.module.exports (/Users/sho/src/nodejs/Polidium/node_modules/url-loader/index.js:18:20)
 @ ./~/css-loader!./~/materialize-css/dist/css/materialize.min.css 6:41235-41301
```

**Comment by nekobato** [comment]
なるほどぃうむ

**Comment by nekobato** [comment]
fixed bab84020e369bbf36da79d24ed2253ad97a2aa8c
